### ISSUE TITLE
Missing Wmo Doodas

### ISSUE THREAD

**Issue by behzad62** [Kruithne/wow.export#162] opened 2021-01-27 07:04 UTC
![MissingDoodas](https://user-images.githubusercontent.com/5605613/105954977-c910b200-608a-11eb-928d-48f4a2fd4443.jpg)

As you can see in the pic, some Wmo-Doodas are not loading in the classic wow when exporting maps. I only was checking classic though.
Thx for this awesome tool btw.

**Comment by Kruithne** [comment] 2021-01-27 12:25
Hey,

Thanks for the report, I've done a little bit of investigation on this. It does appear that some of the objects are missing from the Classic version of the WMO, however they're not missing from the Retail WMO. There are no parsing errors or missing data from what I can see, so I don't think this is an error in wow.export.

I checked on an old alpha client and the objects appear to be there. Something I noticed is that on the Classic version, there is the addition of a small reference marker where one of the troughs is meant to be. My thoughts here are that they were intentionally removed from the WMO and then added in as server-side objects (for reasons unknown) with the marker used for positioning. Potentially related to the scrapped "survival" profession that was intended back in the day? Who knows!

Either way, the only solution right now would either be to manually place the missing objects, or use the retail version of the WMOs which as far as I know are mostly identical and have the objects included.

**Comment by Kruithne** [comment] 2021-01-27 12:35
![DevTools_-_chrome-extensionhjnamambhlpahhgnmkmd_2021-01-27_12-33-43](https://user-images.githubusercontent.com/682348/105991655-fd409e80-609b-11eb-958d-91e031e3519e.png)

UPDATE 2

Further investigation and it turns out that the objects ARE part of the WMO, but they're not M2 files, rather MDL files. Looks like some things got missed when everything was converted. I'll look into getting a fix for this.

**Comment by behzad62** [comment] 2021-01-27 12:42
Thx for the response.
Nice, I am looking forward for your fix then.

**Comment by Kruithne** [comment] 2021-01-27 12:51
Resolved in f17dc1ea90c532877c5bc03ef7d87db43c368f44 (0.1.25). Live update coming momentarily.

**Closed by Kruithne** 2021-01-27 12:51 UTC
Labels: bug, user-report
