### ISSUE TITLE
Blender 3.5 imports modify the UV map

### ISSUE THREAD

**Issue by Symphoneum** [Kruithne/wow.export#393] opened 2023-09-28 14:48 UTC
When using the plugin in Blender 3.5, the UV map is condensed to a single vertex point in the corner of the texture map. Essentially, all vertices are stacked on one point instead of being spread out over the texture as a proper UV would do. This is not an issue in 3.2.2. I have not tested in 3.3 or 3.4 (I haven't downloaded those). 

I was specifically testing on the Legion columns (7lg_legion_columns01 and 7lg_legion_columns02) but it may apply to most models.

**Comment by Kruithne** [comment] 2023-11-05 14:22
Can confirm this is a BMesh regression in Blender for 3.5. It seems this was caught and resolved 7 months ago, can you confirm with a newer version of Blender that it's resolved?

https://projects.blender.org/blender/blender/issues/106430

**Comment by Kruithne** [comment] 2023-11-23 09:57
I've confirmed this is now resolved in Blender. If you run into this issue, ensure you have the latest version of Blender, as the issue is not with wow.export

**Closed by Kruithne** 2023-11-23 09:57 UTC
