### ISSUE TITLE
Exe wont open

### ISSUE THREAD

**Issue by elyriasu** [Kruithne/wow.export#394] opened 2023-10-17 21:25 UTC
Recently downloaded wow.export to replace wowmodelviewer but I can't get the .exe to run. It seems to load for a moment in my file explorer, and then nothing happens, nothing in my task manager to imply its stuck somewhere. Has anyone else had this issue? I tried reinstalling and running as administrator.

**Comment by Kruithne** [comment] 2023-10-17 21:35
A few people have had this issue in the past, it's often related to anti-virus or UAC. Ensure that wow.export is fully extracted from the ZIP file. If it's under a user directory (C:\Users\...) it may be blocked by UAC, try moving it outside of a user directory. Moving it to C:\wow.export should be enough.

If this still isn't working, it's possible that it's being blocked by anti-virus. Try making an exception for the executable in whatever anti-virus software you are using. The source code for wow.export is contained in this GitHub repository, as well as the build process, so if the build was downloaded from this GitHub or our official website, it will be safe.

**Comment by briochie** [comment] 2023-10-18 04:28
@elyriasu where did you download the app from?

**Comment by elyriasu** [comment] 2023-10-18 09:56
Excluded the program from my anti-virus and re-exported the files from the zip to C; but still no dice. I downloaded the file from the official website.

**Comment by elyriasu** [comment] 2023-10-20 01:29
I moved the zip to c: and unzipped it to a folder it created there.

**Comment by briochie** [comment] 2024-01-29 16:06
> it seems as though the release builds weren't tested because they're not producing runnable executables.

If this was true, the discord server would be alive with issues. This is most certainly an issue with your setup in particular.

The app doesn't support linux out of the box, and I'm unsure what requirements wine would have in particular. I recommend asking on the discord to see if someone else is using the same setup.

At any rate, this is most certainly _not_ the same issue as the OP.

**Comment by knuxyl** [comment] 2024-01-29 16:15
> > it seems as though the release builds weren't tested because they're not producing runnable executables.
> 
> If this was true, the discord server would be alive with issues. This is most certainly an issue with your setup in particular.
> 
> The app doesn't support linux out of the box, and I'm unsure what requirements wine would have in particular. I recommend asking on the discord to see if someone else is using the same setup.
> 
> At any rate, this is most certainly _not_ the same issue as the OP.

I doubt that. OP should provide command prompt logs. I bet we're getting roughly the same problem. Something about the executable makes wine think it isn't a proper windows executable.

I was able to fix the linux issue, the updater wouldn't compile but everything else did. It works just fine on my setup so I don't care anymore.

**Comment by briochie** [comment] 2024-01-29 16:17
> I was able to fix the linux issue, the updater wouldn't compile but everything else did.

Glad it's working for you. :)

Would you mind sharing so other people with the same issue can resolve it?

**Comment by Marlamin** [comment] 2024-01-29 16:22
For both OP and @knuxyl, maybe try [installing VC redistributables](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170). However you're going to go about that in Wine I don't know, so good luck with that, but this might fix it for OP as this has been an issue that [has been reported with nwjs in the past](https://github.com/nwjs/nw.js/issues/7803). We haven't been able to reproduce this or get in a debugging session with anyone who has the issue, so it's been hard to figure out an exact fix for.

**Comment by knuxyl** [comment] 2024-01-29 17:20
> > I was able to fix the linux issue, the updater wouldn't compile but everything else did.
> 
> Glad it's working for you. :)
> 
> Would you mind sharing so other people with the same issue can resolve it?

Well I'm on Debian Sid, and I installed node v18.19.0. The updater app won't compile saying it can't find node18, but I realized it was giving this error after it already compiled the main executable.
I'm not sure what should be the actual process for this, but I just took all of the files in the bin directory and put them in the downloaded 0.1.57 windows folder and overwrote everything. If I didn't merge these folders it would load what looked like an example window. I'm sure there's some resources and such that are moved after compilation into the bin folder but I didn't want to dig through all the scripts.
I tested with the CDN option and it loads, views, and exports 3d models just fine. I only have 3.3.5a, not the "Classic"/Rerelease version so it doesn't recognize the installation because of a missing .buildinfo file, which is only provided by the newer clients. I didn't think enough about it when I found this, I assumed Classic actually meant the classic games, but blizzard in their infinite wisdom decided to use "classic" for a "rerelease".

**Comment by briochie** [comment] 2024-01-29 19:00
>  I only have 3.3.5a, not the "Classic"/Rerelease version

wow.export only supports the most recent retail/classic release versions. This isn't a bug, it's intended.

Unless @elyriasu is still having issues, I think this can be closed.

**Closed** 2024-01-29 19:01 UTC

**Comment by knuxyl** [comment] 2024-01-29 19:32
> > I only have 3.3.5a, not the "Classic"/Rerelease version
> 
> wow.export only supports the most recent retail/classic release versions. This isn't a bug, it's intended.
> 
> Unless @elyriasu is still having issues, I think this can be closed.

i thought i made it clear that i was aware of that, and that i didn't assume it was a bug. i even went into detail.

**Comment by briochie** [comment] 2024-01-29 21:11
If you aren't willing to use the app in it's intended way, there isn't much anyone can do in the name of support.

Glad you got it working.
