### ISSUE TITLE
[0.1.29] Doodad sets not always unloading properly once unchecked

### ISSUE THREAD

**Issue by alishahb** [Kruithne/wow.export#185] opened 2021-04-21 18:38 UTC
Doodad sets not always unloading properly once unchecked.

**version**:  0.1.29

**The way to reproduce:**
1. search for *13416.wmo*
2. check/uncheck: 11 12 13 (3rd, 4th, 5th from bottom of the list)
![image](https://user-images.githubusercontent.com/8345328/115604239-d1733480-a2e9-11eb-911d-0c9f0b03538d.png)

**Comment by Kruithne** [comment] 2021-05-01 14:29
This appears to be a temporary visual glitch caused by the asynchronous nature in which we load the models. This occurs when unchecking a set before it has loaded. The effect is not permanent and can be resolve by simply re-toggling the set.

Marking this as WNF as it's minor and easily averted.

**Closed by Kruithne** 2021-05-01 14:29 UTC
